#!/usr/bin/env bash
set -euo pipefail

VERSION="${1:-0.1.0}"
OUT_DIR="${2:-dist}"
GROUP_ID="com.geo.sdk"
ARTIFACT_ID="geo-event-trigger-core-sdk"

BUILD_DIR=".build/artifact"
CLASSES_DIR="$BUILD_DIR/classes"
META_INF_DIR="$BUILD_DIR/META-INF/maven/$GROUP_ID/$ARTIFACT_ID"

rm -rf "$BUILD_DIR"
mkdir -p "$CLASSES_DIR" "$OUT_DIR" "$META_INF_DIR"

javac -d "$CLASSES_DIR" $(find src/main/java -name "*.java" | tr '\n' ' ')

cat > "$META_INF_DIR/pom.properties" <<POMPROPS
#Generated by scripts/build_artifact.sh
groupId=$GROUP_ID
artifactId=$ARTIFACT_ID
version=$VERSION
POMPROPS

cat > "$OUT_DIR/$ARTIFACT_ID-$VERSION.pom" <<POMXML
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>$GROUP_ID</groupId>
  <artifactId>$ARTIFACT_ID</artifactId>
  <version>$VERSION</version>
  <name>geo-event-trigger-core-sdk</name>
  <description>Context intervention core SDK</description>
</project>
POMXML

jar --create --file "$OUT_DIR/$ARTIFACT_ID-$VERSION.jar" -C "$CLASSES_DIR" . -C "$BUILD_DIR" META-INF

echo "Built artifact: $OUT_DIR/$ARTIFACT_ID-$VERSION.jar"
echo "Generated pom: $OUT_DIR/$ARTIFACT_ID-$VERSION.pom"
